### ISSUE TITLE
Ugrade to latest version fails, if version is like *-beta

### ISSUE THREAD

**Issue by Outek** [gaelcolas/Chocolatey#28]
If the chocolatey package have something like *-beta or *-pre in the versionnumber, the upgrade to a full version(latest) fails.

Something like 
```
choco list 7zip --version=18.0-beta -pre
```

```     
--pre, --prerelease
Prerelease - Include Prereleases? Defaults to false.
```
[Chocolatey doc](https://chocolatey.org/docs/commands-install)

**Comment by gaelcolas** [comment]
Do you mean using the DSC resource?
Can you share how you tried, and the error messages?

**Comment by Outek** [comment]
Yes, sure. The issue was more or less a reminder for me, now i can provide some logs.

That's from the dsc log:
```
Cannot convert value "1.2.3.22-pre" to type "System.Version". Error: "Input string was not in a correct format."
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocation
    + PSComputerName        : localhost
```

With chocolatey is look like this:
```
PS C:\> choco list softwareabc
mule 1.2.3.22
```

```
PS C:\> choco list softwareabc -pre -lo
softwareabc 1.2.3.22-pre
```
So basically the version 1.2.3.22 is the "released" version of the package. If the dev or beta package 1.2.3.22-pre is installed and the dsc flag is set to latest, it should be installed. If i do this with chocolatey(choco upgrade softwareabc -y) alone, it is working fine.

**Comment by gaelcolas** [comment]
Hi @Outek 

I think I've fixed this in the `semver` branch: https://ci.appveyor.com/project/gaelcolas/chocolatey/build/artifacts

It should now supports semver (plus an extra **revision** as used in choco/nuGet/.Net) by allowing a more extensive parsing of the versions.
The DSC resource hasn't changed, only the underlying commands have, that should be enough (it calls `Test-ChocolateyPackageIsInstalled`), but I haven't tested via DSC yet (only command line with the commands called by the Resources).

If you get a chance, it'd be great if you could test the DSC bits.

Let me know how it goes.

**Comment by Outek** [comment]
Hi @gaelcolas 
this is working now, thank you.
