### ISSUE TITLE
Add ChocolateyPin DSC Resource

### ISSUE THREAD

**Issue by gaelcolas** [gaelcolas/Chocolatey#4]
It'd be good to be able to use DSC to pin some app so they are not affected by Choco upgrade.

**Comment by Outek** [comment]
Hi Gael

Did you ever start to implement this function?

I recently started with it, but i'm not quite sure how to implement it. My first idea was to implement 4 public functions, Get-ChocolateyPinPackage, Test-ChocolateyPinPackage, Enable-ChocolateyPinPackage and Disable-ChocolateyPinPackage. What do you think about this?

**Comment by gaelcolas** [comment]
No I haven't yet.
I'd call it ChocolateyPin, as you can pin package & version.
https://github.com/chocolatey/choco/wiki/CommandsPin
Enable/disable can work, but maybe a set would do too, and allow for an array of packages to pin.
Params would look like name, version (optional), reason (optional), remove (switch if using a Set).

**Comment by gaelcolas** [comment]
So, I did not know much about how the command worked, so please ignore the message above.

I had a look and took a first quick stab at a Get/Add/Remove set of cmdlets [in my chocopin branch](https://github.com/gaelcolas/Chocolatey/tree/chocopin).

I used Add and Remove because it's closer to the Choco commands.

You still need to add the help for the commands, the tests, and the DSC Resource.

Hope that helps!

**Comment by gaelcolas** [comment]
Forgot to say I don't support `--reason` as per [the choco documentation](https://github.com/chocolatey/choco/wiki/CommandsPin) because it's not an available option my current version (I'm only at 0.10.11, maybe it's a new feature).

If you do implement with --reason, please make sure it's dropped if the version does not have that feature (`Get-ChocolateyVersion` at the top of the Private function `Get-ChocolateyDefaultArgument`, and conditional output within the switch).
It's not needed though, if you don't need it, feel free to leave it for another time.

Hit me up if any question.

**Comment by Outek** [comment]
Thank you, i'll try to get this ready.

**Comment by Outek** [comment]
The Functions are ready, but i'm not sure about the Dsc Resources. 
Should i implement it as a new resource, maybe "ChocolateyPin" or integrate it in "ChocolateyPackage"?

**Comment by gaelcolas** [comment]
Hey, new resources. Thanks
Draft something and let me know I'll review when I get some time

**Comment by Outek** [comment]
I have to fix the tests, but maybe you have early feedback..
https://github.com/Outek/Chocolatey/tree/chocopin

**Comment by gaelcolas** [comment]
Hi @outek,

Easiest for me to (pre) review is if you open a draft PR (I'm afk and mostly on phone these days).
That said the test and set seems good, the Get should return the actual value when doing the Get.
Maybe you looked at one of my resource that has the get poorly implemented, feel free to raise an issue.
Thanks for the good work, keep it up :)

**Comment by gaelcolas** [comment]
Thanks for the contribution @Outek 
Should just merged so it should build & release shortly.
Let me know if any issue.

Fixed in #33
